import type { UserDashboardModel, UserRowModel } from './UserModel';

const signups14 = Array.from({ length: 14 }, (_, i) => `${i + 1}`);
const signupsValues = [16, 17, 18, 19, 18, 20, 22, 21, 23, 24, 26, 27, 29, 30];

export const mockUserRows: UserRowModel[] = [
  {
    id: 'u-1',
    initials: 'AP',
    name: 'Ari Pratama',
    email: 'ari.pratama@mail.com',
    phone: '+62 812-3456-7890',
    plan: 'Maniac',
    planBadgeClass: 'badge badge--primary',
    statusKey: 'back-desk.feature-user.table.row_status_active',
    statusBadgeClass: 'badge badge--success',
    joined: '12 Feb 2026',
  },
  {
    id: 'u-2',
    initials: 'SN',
    name: 'Sari Nurhayati',
    email: 'sari.n@mail.com',
    phone: '+62 821-9876-5432',
    plan: 'Explore',
    planBadgeClass: 'badge badge--muted',
    statusKey: 'back-desk.feature-user.table.row_status_active',
    statusBadgeClass: 'badge badge--success',
    joined: '03 Jan 2026',
  },
  {
    id: 'u-3',
    initials: 'BH',
    name: 'Budi Hartono',
    email: 'budihar@mail.com',
    phone: '+62 817-5544-3322',
    plan: 'Maniac',
    planBadgeClass: 'badge badge--primary',
    statusKey: 'back-desk.feature-user.table.row_status_suspended',
    statusBadgeClass: 'badge badge--warning',
    joined: '27 Nov 2025',
  },
  {
    id: 'u-4',
    initials: 'DI',
    name: 'Dewi Indrayanti',
    email: 'dewi.i@mail.com',
    phone: '+62 813-2211-0099',
    plan: 'Maniac',
    planBadgeClass: 'badge badge--primary',
    statusKey: 'back-desk.feature-user.table.row_status_active',
    statusBadgeClass: 'badge badge--success',
    joined: '08 Sep 2025',
  },
  {
    id: 'u-5',
    initials: 'FS',
    name: 'Fadli Saputra',
    email: 'fadli.s@mail.com',
    phone: '',
    plan: 'Explore',
    planBadgeClass: 'badge badge--muted',
    statusKey: 'back-desk.feature-user.table.row_status_banned',
    statusBadgeClass: 'badge badge--danger',
    joined: '14 Agu 2025',
  },
];

export const mockUserDashboard: UserDashboardModel = {
  stats: [
    {
      id: 'mock-total',
      titleKey: 'back-desk.feature-user.card_total',
      value: '1.248',
      badgeKey: 'back-desk.feature-user.badge_active',
      badgeClass: 'badge--success',
      icon: 'total',
    },
    {
      id: 'mock-premium',
      titleKey: 'back-desk.feature-user.card_premium',
      value: '312',
      badgeKey: 'back-desk.feature-user.badge_maniac_plan',
      badgeClass: 'badge--primary',
      icon: 'premium',
    },
    {
      id: 'mock-new-month',
      titleKey: 'back-desk.feature-user.card_new_month',
      value: '87',
      badgeKey: 'back-desk.feature-user.badge_mom',
      badgeClass: 'badge--success',
      icon: 'newMonth',
    },
    {
      id: 'mock-inactive',
      titleKey: 'back-desk.feature-user.card_inactive',
      value: '34',
      badgeKey: 'back-desk.feature-user.badge_30d_inactive',
      badgeClass: 'badge--muted',
      icon: 'inactive',
    },
  ],
  chartsPrimary: [
    {
      titleKey: 'back-desk.feature-user.chart_signups_title',
      subtitleKey: 'back-desk.feature-user.chart_signups_subtitle',
      preset: 'user-signups',
      labels: signups14,
      values: signupsValues,
      badgeLiteral: '+24%',
      badgeVariant: 'success',
    },
    {
      titleKey: 'back-desk.feature-user.chart_status_title',
      subtitleKey: 'back-desk.feature-user.chart_status_subtitle',
      preset: 'user-status',
      labels: ['Aktif', 'Trial', 'Suspend', 'Banned'],
      values: [980, 120, 45, 103],
      badgeKey: 'back-desk.feature-user.chart_status_badge',
      badgeVariant: 'muted',
    },
    {
      titleKey: 'back-desk.feature-user.chart_plan_title',
      subtitleKey: 'back-desk.feature-user.chart_plan_subtitle',
      preset: 'user-plan',
      badgeKey: 'back-desk.feature-user.chart_plan_badge',
      badgeVariant: 'primary',
    },
    {
      titleKey: 'back-desk.feature-user.chart_retention_title',
      subtitleKey: 'back-desk.feature-user.chart_retention_subtitle',
      preset: 'user-retention',
      badgeKey: 'back-desk.feature-user.chart_retention_badge',
      badgeVariant: 'success',
    },
  ],
  chartsSecondary: [
    {
      titleKey: 'back-desk.feature-user.chart_growth_title',
      subtitleKey: 'back-desk.feature-user.chart_growth_subtitle',
      preset: 'user-growth',
      values: [110, 128, 137, 149, 165, 178, 194],
      badgeLiteral: '+18%',
      badgeVariant: 'success',
    },
    {
      titleKey: 'back-desk.feature-user.chart_revenue_title',
      subtitleKey: 'back-desk.feature-user.chart_revenue_subtitle',
      preset: 'revenue-monthly',
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
      values: [12, 15, 14, 18, 22, 24],
      badgeLiteral: 'Rp 45.2M',
      badgeVariant: 'primary',
    },
    {
      titleKey: 'back-desk.feature-user.chart_dist_plan_title',
      subtitleKey: 'back-desk.feature-user.chart_dist_plan_subtitle',
      preset: 'plan-doughnut',
      badgeKey: 'back-desk.feature-user.chart_plan_badge',
      badgeVariant: 'primary',
    },
    {
      titleKey: 'back-desk.feature-user.chart_category_title',
      subtitleKey: 'back-desk.feature-user.chart_category_subtitle',
      preset: 'category-radar',
      badgeKey: 'back-desk.feature-user.chart_category_badge',
      badgeVariant: 'success',
    },
  ],
  rows: mockUserRows,
  pagination: null,
  totalUsersInDb: null,
};
